### ISSUE TITLE
install from source instructions

### ISSUE THREAD

**Issue by fommil** [rbray89/EnvironmentalVisualEnhancements#10]
This looks amazing, and I'd like to track the github repo for updates... but I'm confused how to install this way. You have a `GameData` directory under the root, where is everything supposed to go?

**Comment by WazWaz** [comment]
1. Install Mono (for pdb2mdb)
2. Open the .sln in Visual Studio
3. Change the KSP directory in the Prebuild Build Event in the Util project properties
4. Change the KSP directory in the Post Build Event in the _BuildManager project properties
5. Rebuild Solution

This builds everything and installs it in your KSP directory.

(I'm mostly documenting this for my own benefit of remembering)

**Comment by WazWaz** [comment]
Update to this, just create a LocalSetup.csproj at the top level, like this:

```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="14.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
<PropertyGroup>
    <KSPDir>C:\KSP\KSP_1.4</KSPDir>
</PropertyGroup>
</Project>

```

And rebuild from VS.
