### ISSUE TITLE
.90

### ISSUE THREAD

**Issue by calvinjuarez** [rbray89/EnvironmentalVisualEnhancements#23]
Is this mod compatible with KSP .90?

If so, the [forum page](http://forum.kerbalspaceprogram.com/threads/55905-0-22-Beta-1-City-Lights-and-Clouds) really ought to be updated ([0.24–0.90]) to indicate that.  (At the moment it just says [0.24].)

If not, is .90 support planned?

**Comment by EoD** [comment]
As there has been a new version which is compatible with 1.0.5 this issue can be closed.
