### ISSUE TITLE
You really shouldn't check zip files into git.

### ISSUE THREAD

**Issue by rskennymore** [rbray89/EnvironmentalVisualEnhancements#41]
This tiny software project shouldn't take 20 minutes to clone and take up over a GB of hard drive space. There's gotta be a better way to host your release files...

**Comment by rbray89** [comment]
Normally I'd agree, but that is my way to generate intermediate build releases. I haven't found a way to autogenerate github releases. If you have a good method of doing that, id purge the zip files from the repo.
