### ISSUE TITLE
I have installed EVE but it doesnt work

### ISSUE THREAD

**Issue by legendkiller1** [rbray89/EnvironmentalVisualEnhancements#52]
I placed the content of the 2 zip files in the GameData folder but the mod doesnt work. I am using version 1.1.2, x64 of KSP 
[output_log.txt](https://github.com/rbray89/EnvironmentalVisualEnhancements/files/271465/output_log.txt)
![screenshot of the gamedata folder](https://cloud.githubusercontent.com/assets/19438369/15376183/1751bf58-1d5c-11e6-8a9d-a99735907ce2.png)

**Comment by NoMrBond** [comment]
The two folders go into the \GameData\ folder, not the \GameData\Squad\ folder

**Comment by legendkiller1** [comment]
Ok that fixed it, Having previously installed Kerbal Engineer in the GameData/Squad I thought that EVE needs to be installed there too

**Comment by legendkiller1** [comment]
How can I edit the configs to have more clouds and make the planet look much better?

**Comment by NoMrBond** [comment]
Mod folders should go in \GameData\, the effect of alternate placements can be unpredictable and may produce undesirable outcomes.

I haven't looked at the cloud configurations but there are packages which contain alternate cloud configurations for E.V.E. such as Astronomers Pack, SVE and KSPRC which you could review to get ideas about the texture and config settings people are using.
